line-length = 100
fix = false
output-format = "grouped"

extend-exclude = [
    "__pycache__",
    ".cache",
]

[lint]
select = [
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "D",    # pydocstyle/flake8-docstrings
    "F",    # Pyflakes
    "FIX",  # flake8-fixme
    "N",    # pep8-naming
]

ignore = [
    # pydocstyle
    "D100",
    "D104",
    "D105",
    "D107",
    "D203",
    "D212",
    "D214",
    "D215",
    "D301",
    "D400",
    "D401",
    "D402",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D412",
    "D413",
    "D414",
    "D416",
    "D417",
    # pep8-naming
    "N802",
    "N806",
    "N815",
]

[lint.per-file-ignores]
"pylox/protocols/*.py" = ["D101", "D102",]
"pylox/ast_printer.py" = ["D102",]
"pylox/builtins/py_builtins.py" = ["D101", "D102",]
"pylox/callable.py" = ["D101", "D102"]
"pylox/error.py" = ["D101",]
"pylox/grammar.py" = ["D101", "D102",]
"pylox/interpreter.py" = ["D102",]
"pylox/lox.py" = ["B008",]
"pylox/resolver.py" = ["D101", "D102",]
"tests/*/test_*.py" = ["D101", "D103",]
"tool/generate_ast.py" = ["B008",]
"tool/generate_tests.py" = ["B008"]

[lint.flake8-bugbear]
extend-immutable-calls = [
    # Typer CLI
    "typer.Option",
    "typer.Argument",
]
