# THIS FILE HAS BEEN AUTOGENERATED
import typing as t

import attr


@attr.s(slots=True)
class Expr:
    pass


@attr.s(slots=True)
class Binary(Expr):
    expr_left: t.Any = attr.ib()
    token_operator: t.Any = attr.ib()
    expr_right: t.Any = attr.ib()


@attr.s(slots=True)
class Grouping(Expr):
    expr_expression: t.Any = attr.ib()


@attr.s(slots=True)
class Literal(Expr):
    object_value: t.Any = attr.ib()


@attr.s(slots=True)
class Unary(Expr):
    token_operator: t.Any = attr.ib()
    expr_right: t.Any = attr.ib()
